# Simple CD

name: push_cd

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout main
      uses: actions/checkout@v3.0.0
      - name: Build Zola 
        uses: shalzz/zola-deploy-action@v0.17.1
        env:
          BUILD_DIR: build
          BUILD_ONLY: true
      - name: Copy folder to where nginx expects it to be
        run: cp -r ${{secrets.COPY_FROM_FOLDER}} ${{secrets.COPY_TO_FOLDER}}
      