# Simple CD

name: push_cd

on:
  push
    # branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Build Zola 
        uses: shalzz/zola-deploy-action@v0.17.1
        env:
          OUT_DIR: target
          BUILD_ONLY: true

      - name: Copy folder to where nginx expects it to be
        run: cp -r ./target/ ${{secrets.COPY_TO_FOLDER}}
      