name: Zola Build and Deploy

on:
  push:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Zola 
        run: /snap/bin/zola build -o www

      - name: Copy to deployment folder
        run: chown nyadiia:nyadiia www
        run: cp -rf www /home/nyadiia/webserver/config/

  build:
    runs-on: self-hosted
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check Zola Build 
        run: /snap/bin/zola check --drafts
