# Simple CD

name: push_cd

on:
  push:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Build Zola 
        run: /snap/bin/zola build

      - name: Copy to deployment folder
        run: cp -r ./public/ /var/www/main

      - name: Reload nginx
        run: systemctl reload nginx

  build:
    runs-on: self-hosted
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Build Zola 
        run: /snap/bin/zola build