name: Zola Build and Deploy

on:
  push:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Zola 
        run: /snap/bin/zola build -o main

      - name: Copy to deployment folder
        run: cp -rf main /var/www/

      - name: Reload nginx
        run: systemctl reload nginx

  build:
    runs-on: self-hosted
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check Zola Build 
        run: /snap/bin/zola check --drafts
