# Simple CD

name: push_cd

on:
  push
    # branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Build Zola 
        run: /snap/bin/zola build

      - name: Copy folder to where nginx expects it to be
        run: cp -r ./public/ ${{secrets.COPY_TO_FOLDER}}